(function () {
  const extraLoadouts = [
    { mode: "warzone-ranked", name: "Ryden 45K", role: "Close-Range-SMG mit Fokus auf Mobility, Magazingroesse und sicherem Handling.", secondary: "DS20 Mirage", buildCode: "S01-AUY8U-EXTF1-1", attachments: ["Optic: Lethal Tools ELO", "Barrel: 12\" Vienna Barrel", "Magazine: Forward Breach Mag", "Rear Grip: Eruption Grip", "Stock: MFS Full Stock+"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
    { mode: "warzone-ranked", name: "Sturmwolf 45", role: "Close-Range-SMG fuer aggressive Pushes mit stabilem Recoil.", secondary: "DS20 Mirage", buildCode: "", attachments: ["Optic: Lethal Tools ELO", "Muzzle: Hawker Series 45", "Barrel: Long Barrel", "Magazine: Extended Mag II", "Fire Mods: Buffer Spring"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
    { mode: "warzone-ranked", name: "Dravec 45", role: "Close-Range-SMG fuer schnelle Entries und stabile Trades.", secondary: "DS20 Mirage", buildCode: "", attachments: ["Muzzle: Compensator", "Barrel: Ranger Barrel", "Underbarrel: Lightweight Handstop", "Magazine: Fast Mag", "Stock: Raider Stock"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
    { mode: "warzone-ranked", name: "EGRT-17", role: "Long-Range-AR mit Suppressor, Recoil-Control und grossem Magazin.", secondary: "Kogot-7", buildCode: "", attachments: ["Optic: FANG HoverPoint ELO", "Muzzle: Monolithic Suppressor", "Barrel: Reinforced Barrel", "Underbarrel: VAS Convergence Foregrip", "Magazine: Extended Mag II"], perks: ["Scavenger", "Quick Fix", "Survivor"] },
    { mode: "warzone-ranked", name: "REV-46", role: "Close-Range-SMG als Warzone-Contender mit sauberer Zielaufnahme.", secondary: "DS20 Mirage", buildCode: "", attachments: ["Optic: Lethal Tools ELO", "Muzzle: Hawker Series 45", "Barrel: Caudal Target Barrel", "Magazine: Komodo Drum Mag", "Fire Mods: Recoil Sync Unit"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
    { mode: "warzone-ranked", name: "Maddox RFB", role: "Long-Range-AR fuer kontrollierte Mid- bis Long-Range-Fights.", secondary: "Kogot-7", buildCode: "", attachments: ["Optic: FANG HoverPoint ELO", "Muzzle: Monolithic Suppressor", "Barrel: Reinforced Long Barrel", "Underbarrel: VAS Convergence Foregrip", "Magazine: Extended Mag II"], perks: ["Scavenger", "Quick Fix", "Survivor"] },
    { mode: "warzone-ranked", name: "Peacekeeper Mk1", aliases: ["Peacekeeper MK1"], role: "Long-Range-AR mit schnellem Handling und stabilem Recoil.", secondary: "Kogot-7", buildCode: "", attachments: ["Muzzle: Ported Compensator", "Barrel: Balanced Barrel", "Underbarrel: Precision Foregrip", "Rear Grip: Quickdraw Grip", "Stock: Agile Stock"], perks: ["Scavenger", "Quick Fix", "Survivor"] },
    { mode: "warzone-ranked", name: "M15 MOD 0", role: "Long-Range-AR mit starkem Allround-Profil.", secondary: "Kogot-7", buildCode: "", attachments: ["Optic: Reflex ELO", "Muzzle: Compensator", "Barrel: Reinforced Long Barrel", "Underbarrel: Vertical Foregrip", "Rear Grip: Quickdraw Grip"], perks: ["Scavenger", "Quick Fix", "Survivor"] },
    { mode: "warzone-ranked", name: "X9 Maverick", role: "Long-Range-AR mit Reichweite, Bullet Velocity und ruhigem Rueckstoss.", secondary: "Kogot-7", buildCode: "", attachments: ["Optic: FANG HoverPoint ELO", "Muzzle: Monolithic Suppressor", "Barrel: Long Barrel", "Underbarrel: Vertical Foregrip", "Magazine: Extended Mag II"], perks: ["Scavenger", "Quick Fix", "Survivor"] },
    { mode: "warzone-ranked", name: "M8A1", role: "Sniper-Support-Marksman-Build mit Full-Auto-Conversion.", secondary: "Kogot-7", buildCode: "", attachments: ["Muzzle: VAS 5.56 Suppressor", "Barrel: M8A1 Autostrike-X8 Conversion", "Stock: MFS Striker Tactical Stock", "Magazine: Redline Capacity Drum", "Rear Grip: K&S Raze Grip"], perks: ["Scavenger", "Quick Fix", "Survivor"] },
    { mode: "warzone-ranked", name: "Hawker HX", role: "Sniper-Build fuer schnelle Long-Range-Picks.", secondary: "Ryden 45K", buildCode: "", attachments: ["Muzzle: Monolithic Suppressor", "Barrel: Reinforced Barrel", "Stock: Precision Stock", "Rear Grip: Quickdraw Grip", "Fire Mods: Overpressured"], perks: ["Survivor", "Smoke Grenade", "Fast Hands"] },
    { mode: "warzone-ranked", name: "VS Recon", role: "Sniper-Build mit Fokus auf Velocity und Aim-Stability.", secondary: "Ryden 45K", buildCode: "", attachments: ["Muzzle: Monolithic Suppressor", "Barrel: Reinforced Long Barrel", "Stock: Heavy Stock", "Rear Grip: Ergonomic Grip", "Fire Mods: Overpressured"], perks: ["Survivor", "Smoke Grenade", "Fast Hands"] },
    { mode: "bo7-ranked", name: "VS Recon", role: "Sniper-Build mit Fokus auf Velocity und Aim-Stability.", secondary: "Dravec 45", buildCode: "", attachments: ["Muzzle: Monolithic Suppressor", "Barrel: Reinforced Long Barrel", "Stock: Heavy Stock", "Rear Grip: Ergonomic Grip", "Fire Mods: Overpressured"], perks: ["Dexterity", "Fast Hands", "Tac Mask"] },
    { mode: "warzone-ranked", name: "Swordfish A1", role: "Sniper-/Marksman-Setup fuer praezise Picks auf Range.", secondary: "Ryden 45K", buildCode: "", attachments: ["Optic: FANG HoverPoint ELO", "Muzzle: Monolithic Suppressor", "Barrel: Reinforced Barrel", "Underbarrel: Precision Foregrip", "Magazine: Extended Mag"], perks: ["Survivor", "Smoke Grenade", "Fast Hands"] },
    { mode: "warzone-ranked", name: "Sokol 545", role: "Long-Range-LMG mit Kontrolle, Reichweite und grossem Magazin.", secondary: "Kogot-7", buildCode: "", attachments: ["Optic: Greaves AccuSpot 3x", "Muzzle: Monolithic Suppressor", "Barrel: Long Barrel", "Underbarrel: Bowen Sentry Foregrip", "Rear Grip: Control Grip"], perks: ["Scavenger", "Quick Fix", "Survivor"] },
    { mode: "warzone-ranked", name: "RK-9", role: "Close-Range-SMG fuer mobile Fights.", secondary: "DS20 Mirage", buildCode: "", attachments: ["Optic: Lethal Tools ELO", "Muzzle: Hawker Series 45", "Barrel: Long Barrel", "Magazine: Extended Mag II", "Stock: Raider Stock"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
    { mode: "bo7-ranked", name: "MPC-25", role: "Close-Range-SMG mit starkem Entry-Profil.", secondary: "M15 MOD 0", buildCode: "", attachments: ["Muzzle: K&S Compensator", "Barrel: 14.5\" VAS Ashe Barrel", "Underbarrel: Zero Shift Handstop", "Magazine: MPC Overload Drum", "Fire Mods: Recoil Sync Unit"], perks: ["Dexterity", "Fast Hands", "Flak Jacket"] },
    { mode: "warzone-ranked", name: "XM325", role: "Long-Range-LMG als stabiler B-Tier-Beam.", secondary: "Kogot-7", buildCode: "", attachments: ["Optic: Greaves AccuSpot 3x", "Muzzle: Monolithic Suppressor", "Barrel: Reinforced Long Barrel", "Underbarrel: Vertical Foregrip", "Magazine: Extended Mag"], perks: ["Scavenger", "Quick Fix", "Survivor"] },
    { mode: "warzone-ranked", name: "XR-3 Ion", role: "Sniper-Build mit Fokus auf Velocity und Handling.", secondary: "Ryden 45K", buildCode: "", attachments: ["Muzzle: Monolithic Suppressor", "Barrel: Long Barrel", "Stock: Precision Stock", "Rear Grip: Quickdraw Grip", "Fire Mods: Overpressured"], perks: ["Survivor", "Smoke Grenade", "Fast Hands"] },
    { mode: "warzone-ranked", name: "Shadow SK", role: "Sniper-Build fuer kontrollierte Long-Range-Picks.", secondary: "Ryden 45K", buildCode: "", attachments: ["Muzzle: Monolithic Suppressor", "Barrel: Reinforced Barrel", "Stock: Heavy Stock", "Rear Grip: Ergonomic Grip", "Fire Mods: Overpressured"], perks: ["Survivor", "Smoke Grenade", "Fast Hands"] },
    { mode: "warzone-ranked", name: "M34 Novaline", role: "Marksman-/Sniper-Support-Setup fuer Praezision auf Distanz.", secondary: "Ryden 45K", buildCode: "", attachments: ["Optic: FANG HoverPoint ELO", "Muzzle: Monolithic Suppressor", "Barrel: Reinforced Barrel", "Underbarrel: Precision Foregrip", "Rear Grip: Quickdraw Grip"], perks: ["Survivor", "Smoke Grenade", "Fast Hands"] },
    { mode: "warzone-ranked", name: "Warden 308", role: "Marksman-Build mit stabiler Lane-Kontrolle.", secondary: "Ryden 45K", buildCode: "", attachments: ["Optic: FANG HoverPoint ELO", "Muzzle: Monolithic Suppressor", "Barrel: Reinforced Barrel", "Underbarrel: Vertical Foregrip", "Magazine: Extended Mag"], perks: ["Survivor", "Smoke Grenade", "Fast Hands"] },
    { mode: "warzone-ranked", name: "1911", role: "Close-Range-Pistol-Setup fuer schnelle Secondary-Fights.", secondary: "DS20 Mirage", buildCode: "", attachments: ["Muzzle: Suppressor", "Barrel: Long Barrel", "Magazine: Extended Mag", "Rear Grip: Quickdraw Grip", "Fire Mods: Rapid Fire"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
    { mode: "warzone-ranked", name: "CODA 9", role: "Close-Range-Pistol-Setup mit schnellem Handling.", secondary: "DS20 Mirage", buildCode: "", attachments: ["Muzzle: Suppressor", "Barrel: Reinforced Barrel", "Magazine: Extended Mag", "Rear Grip: Quickdraw Grip", "Fire Mods: Rapid Fire"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
    { mode: "warzone-ranked", name: "Velox 5.7", role: "Close-Range-Pistol-Setup fuer Mobility und Magazingroesse.", secondary: "DS20 Mirage", buildCode: "", attachments: ["Muzzle: Suppressor", "Barrel: Long Barrel", "Magazine: Extended Mag", "Rear Grip: Ergonomic Grip", "Fire Mods: Rapid Fire"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
    { mode: "warzone-ranked", name: "Jager 45", aliases: ["J\u00e4ger 45"], role: "Close-Range-Pistol-Setup.", secondary: "DS20 Mirage", buildCode: "", attachments: ["Muzzle: Suppressor", "Barrel: Reinforced Barrel", "Magazine: Extended Mag", "Rear Grip: Quickdraw Grip", "Fire Mods: Rapid Fire"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
    { mode: "bo7-ranked", name: "Jager 45", aliases: ["J\u00e4ger 45"], role: "Close-Range-Pistol-Setup.", secondary: "M15 MOD 0", buildCode: "", attachments: ["Muzzle: Suppressor", "Barrel: Reinforced Barrel", "Magazine: Extended Mag", "Rear Grip: Quickdraw Grip", "Fire Mods: Rapid Fire"], perks: ["Dexterity", "Fast Hands", "Tac Mask"] },
    { mode: "warzone-ranked", name: "A.R.C. M1", role: "Launcher: keine klassischen Waffenaufsaetze verfuegbar.", secondary: "Kogot-7", buildCode: "", attachments: ["Slot: Launcher", "Aufsaetze: nicht verfuegbar", "Empfehlung: als Utility-Secondary spielen"], perks: ["Scavenger", "Quick Fix", "Survivor"] },
    { mode: "warzone-ranked", name: "Flatline MK.II", role: "Melee: keine klassischen Waffenaufsaetze verfuegbar.", secondary: "DS20 Mirage", buildCode: "", attachments: ["Slot: Melee", "Aufsaetze: nicht verfuegbar", "Empfehlung: Mobility-Perks nutzen"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
    { mode: "warzone-ranked", name: "AAROW 109", role: "Launcher: keine klassischen Waffenaufsaetze verfuegbar.", secondary: "Kogot-7", buildCode: "", attachments: ["Slot: Launcher", "Aufsaetze: nicht verfuegbar", "Empfehlung: Utility-Secondary"], perks: ["Scavenger", "Quick Fix", "Survivor"] },
    { mode: "warzone-ranked", name: "KNIFE", role: "Melee: keine klassischen Waffenaufsaetze verfuegbar.", secondary: "DS20 Mirage", buildCode: "", attachments: ["Slot: Melee", "Aufsaetze: nicht verfuegbar", "Empfehlung: Mobility-Perks nutzen"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
    { mode: "warzone-ranked", name: "Ballistic Knife", role: "Melee/Special: keine klassischen Waffenaufsaetze verfuegbar.", secondary: "DS20 Mirage", buildCode: "", attachments: ["Slot: Melee", "Aufsaetze: nicht verfuegbar", "Empfehlung: Mobility-Perks nutzen"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
    { mode: "warzone-ranked", name: "NX Ravager", role: "Special Weapon: keine klassischen Waffenaufsaetze verfuegbar.", secondary: "Kogot-7", buildCode: "", attachments: ["Slot: Special", "Aufsaetze: nicht verfuegbar", "Empfehlung: als Utility-Pick spielen"], perks: ["Scavenger", "Quick Fix", "Survivor"] },
    { mode: "warzone-ranked", name: "H311-SAW", role: "Melee: keine klassischen Waffenaufsaetze verfuegbar.", secondary: "DS20 Mirage", buildCode: "", attachments: ["Slot: Melee", "Aufsaetze: nicht verfuegbar", "Empfehlung: Mobility-Perks nutzen"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
    { mode: "warzone-ranked", name: "GDL Havoc", role: "Special Weapon: keine klassischen Waffenaufsaetze verfuegbar.", secondary: "Kogot-7", buildCode: "", attachments: ["Slot: Special", "Aufsaetze: nicht verfuegbar", "Empfehlung: Utility-Secondary"], perks: ["Scavenger", "Quick Fix", "Survivor"] },
    { mode: "warzone-ranked", name: "Siren", role: "Special Weapon: keine klassischen Waffenaufsaetze verfuegbar.", secondary: "Kogot-7", buildCode: "", attachments: ["Slot: Special", "Aufsaetze: nicht verfuegbar", "Empfehlung: Utility-Secondary"], perks: ["Scavenger", "Quick Fix", "Survivor"] },
    { mode: "warzone-ranked", name: "Katana", role: "Melee: keine klassischen Waffenaufsaetze verfuegbar.", secondary: "DS20 Mirage", buildCode: "", attachments: ["Slot: Melee", "Aufsaetze: nicht verfuegbar", "Empfehlung: Mobility-Perks nutzen"], perks: ["Mountaineer", "Quick Fix", "Stim Shot"] },
  ];

  const slug = (value) => String(value || "").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/mk\./g, "mk").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

  function legacyLoadouts() {
    try {
      const request = new XMLHttpRequest();
      request.open("GET", `script.js?v=${Date.now()}`, false);
      request.send(null);
      if (request.status < 200 || request.status >= 300) return [];
      const match = request.responseText.match(/const loadouts\s*=\s*(\[[\s\S]*?\]);\s*(?:window\.loadouts\s*=|const modeConfig\s*=)/);
      if (!match) return [];
      const parsed = new Function(`"use strict"; return ${match[1]};`)();
      return Array.isArray(parsed) ? parsed : [];
    } catch {
      return [];
    }
  }

  const byModeAndName = new Map();
  [...legacyLoadouts(), ...extraLoadouts].forEach((loadout) => {
    const names = [loadout.name, ...(loadout.aliases || [])];
    names.forEach((name) => byModeAndName.set(`${loadout.mode}:${slug(name)}`, { ...loadout, name }));
  });

  window.loadouts = [...byModeAndName.values()];
}());
